spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: library
mongock:
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.otus.catalog.changelogs
  mongo-db:
    write-concern:
      journal: false
    read-concern: local

logging:
  level:
    com.github.cloudyrock.mongock: debug
    root: info